"""Unit tests for PathBuilder class."""

import pytest
from pathlib import Path
from datetime import datetime
from src.path_builder import PathBuilder


class TestPathBuilder:
    """Test suite for PathBuilder class."""
    
    def test_build_main_save_path_basic(self):
        """Test main save path construction with basic username."""
        username = "TestUser"
        path = PathBuilder.build_main_save_path(username)
        
        expected = Path(r"C:\Users\TestUser\AppData\Roaming\Glaiel Games\Mewgenics\76561197960287930\saves\steamcampaign01.sav")
        assert path == expected
    
    def test_build_main_save_path_different_usernames(self):
        """Test that different usernames produce different paths."""
        path1 = PathBuilder.build_main_save_path("User1")
        path2 = PathBuilder.build_main_save_path("User2")
        
        assert path1 != path2
        assert "User1" in str(path1)
        assert "User2" in str(path2)
    
    def test_build_backup_directory_path(self):
        """Test backup directory path construction."""
        username = "TestUser"
        path = PathBuilder.build_backup_directory_path(username)
        
        expected = Path(r"C:\Users\TestUser\AppData\Roaming\Glaiel Games\Mewgenics\76561197960287930\saves\backups")
        assert path == expected
    
    def test_build_backup_filename(self):
        """Test backup filename generation with timestamp."""
        timestamp = datetime(2024, 1, 15, 14, 30)
        filename = PathBuilder.build_backup_filename(timestamp)
        
        assert filename == "steamcampaign01_2024-01-15_14-30.savbackup"
    
    def test_build_backup_filename_different_timestamps(self):
        """Test that different timestamps produce different filenames."""
        ts1 = datetime(2024, 1, 15, 14, 30)
        ts2 = datetime(2024, 1, 16, 10, 45)
        
        filename1 = PathBuilder.build_backup_filename(ts1)
        filename2 = PathBuilder.build_backup_filename(ts2)
        
        assert filename1 != filename2
    
    def test_parse_backup_timestamp_valid(self):
        """Test parsing valid backup filename."""
        filename = "steamcampaign01_2024-01-15_14-30.savbackup"
        timestamp = PathBuilder.parse_backup_timestamp(filename)
        
        assert timestamp is not None
        assert timestamp == datetime(2024, 1, 15, 14, 30)
    
    def test_parse_backup_timestamp_invalid_format(self):
        """Test parsing invalid backup filename returns None."""
        invalid_filenames = [
            "steamcampaign01.sav",
            "steamcampaign01_2024-01-15.savbackup",
            "backup_2024-01-15_14-30.savbackup",
            "steamcampaign01_2024-13-15_14-30.savbackup",  # Invalid month
            "random_file.txt",
        ]
        
        for filename in invalid_filenames:
            timestamp = PathBuilder.parse_backup_timestamp(filename)
            assert timestamp is None, f"Expected None for {filename}"
    
    def test_parse_backup_timestamp_roundtrip(self):
        """Test that building and parsing a filename preserves the timestamp."""
        original_timestamp = datetime(2024, 3, 20, 9, 15)
        filename = PathBuilder.build_backup_filename(original_timestamp)
        parsed_timestamp = PathBuilder.parse_backup_timestamp(filename)
        
        assert parsed_timestamp == original_timestamp
    
    def test_constants_defined(self):
        """Test that all required constants are defined."""
        assert hasattr(PathBuilder, 'GAME_DIRECTORY_TEMPLATE')
        assert hasattr(PathBuilder, 'MAIN_SAVE_FILENAME')
        assert hasattr(PathBuilder, 'BACKUP_SUBDIRECTORY')
        assert hasattr(PathBuilder, 'BACKUP_FILENAME_PATTERN')
        
        assert PathBuilder.MAIN_SAVE_FILENAME == "steamcampaign01.sav"
        assert PathBuilder.BACKUP_SUBDIRECTORY == "backups"
    
    def test_backup_filename_pattern_matches_generated_files(self):
        """Test that the pattern constant matches filenames generated by build_backup_filename."""
        import re
        
        timestamp = datetime(2024, 1, 15, 14, 30)
        filename = PathBuilder.build_backup_filename(timestamp)
        
        pattern = PathBuilder.BACKUP_FILENAME_PATTERN
        assert re.match(pattern, filename), f"Generated filename {filename} doesn't match pattern {pattern}"
